# The peers to generate the group
[groupPeers]
peers=["192.168.107.129:20200", "192.168.107.129:20201"]

# The consensus configuration of the generated group
[consensus]
# The sealerList
# sealerList=[]

[genesis]
# The genesis timestamp, It is recommended to set to the current utcTime, which must be greater than 0
# timestamp = ""